### ISSUE TITLE
?url=https://nytimes.com returns blank image

### ISSUE THREAD

**Issue by ahmetb** [as-a-service/screenshot#1]
https://screenshot.as-a-service.dev/?url=https://nytimes.com
https://screenshot.as-a-service.dev/?url=https://www.nytimes.com

**Comment by steren** [comment]
It's slow, but it works for me:
![image](https://user-images.githubusercontent.com/360895/75098274-f98dc900-5568-11ea-9822-478c5ec532d8.png)

I guess this is an issue with Headless Chrome on Cloud Run, which is known to be slow at the moment.
